# Generated by Django 5.2.7 on 2026-03-13 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0016_alter_balancepayment_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstogate",
            name="Member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_to_member",
                to="Members.memberdata",
            ),
        ),
        migrations.AlterField(
            model_name="memberdata",
            name="Email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="Batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batch_time",
                to="Members.batch_db",
            ),
        ),
    ]
